version: "3.8"

services:
  shop_db_test:
    image: mongo
    container_name: shop_db_test
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  shop_cache_test:
    image: redis:5-alpine
    container_name: shop_cache_test
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - 6379:6379
    env_file:
      - .env
    