version: "3.8"

services:
  shop_api:
    image: shop_api
    container_name: shop_api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    command: sh /app/start.sh
    depends_on:
      - shop_db
      - shop_cache
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ${ENV_FILE:-.noenv}
    
  shop_db:
    image: mongo
    container_name: shop_db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  shop_cache:
    image: redis:5-alpine
    container_name: shop_cache
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - ${ENV_FILE:-.noenv}