export enum RedisCacheKeys {
  GET_USER = 'GET_USER',
  LIST_USERS = 'LIST_USERS',
  AUTH_PASS = 'AUTH_PASS',
  LIMIT_REQUESTS = 'LIMIT_REQUESTS',
  GET_ITEM = 'GET_ITEM',
  LIST_ITEMS = 'LIST_ITEMS',
  GET_CART = 'GET_CART',
  LIST_WISHLIST = 'LIST_WISHLIST',
  GET_ORDER = 'GET_ORDER',
  LIST_ORDERS = 'LIST_ORDERS',
  GET_TRANSACTION = 'GET_TRANSACTION',
  LIST_TRANSACTIONS = 'LIST_TRANSACTIONS'
}
